### ISSUE TITLE
Is this patcher really safe?

### ISSUE THREAD

**Issue by codingfornoobs** [KuromeSan/FlashPatcher#16] opened 2021-06-03 21:15 UTC
Because when i open it it always says 'Dangerous file: This program can harm your computer. Even personal information can be at risk.'

**Comment by LiEnby** [comment] 2021-06-05 09:27
it says that for anything that gets detected by Windows Defender, but it just gets detected as "HackTool.Win32/Patcher" or whatever

**Comment by LiEnby** [comment] 2021-06-11 02:58
Duplicate of #8

**Closed as completed by LiEnby** 2021-06-11 02:58 UTC
